# Generated by Django 6.0.1 on 2026-02-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('event_date', models.DateField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=100)),
                ('asset', models.ImageField(blank=True, default='event_asset/default.jpg', null=True, upload_to='event_asset')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.category')),
            ],
        ),
    ]
