# Generated by Django 6.0.1 on 2026-02-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='event_date',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
