# Generated by Django 6.0.1 on 2026-02-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_event_attended_event_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, null=True, upload_to='tasks_asset'),
        ),
    ]
