# Generated by Django 6.0.1 on 2026-02-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='tasks_asset/default_img.jpg', null=True, upload_to='event_asset'),
        ),
    ]
