# Generated by Django 6.0.1 on 2026-02-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
